name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Copy
        run: |
          mkdir out
          cp ./resume.pdf ./out/resume.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: out/resume.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: echen52
          GIT_CONFIG_EMAIL: echen52@illinois.edu
